# Generated by Django 5.0.6 on 2024-09-18 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('commande_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_id', models.IntegerField()),
                ('date_commande', models.DateField()),
                ('statut', models.CharField(max_length=50)),
                ('total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PrestataireDeLivraison',
            fields=[
                ('prestataire_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('statut_livraison', models.CharField(max_length=50)),
                ('numero_suivi', models.CharField(max_length=100)),
                ('date_envoi', models.DateField()),
                ('date_livraison', models.DateField(blank=True, null=True)),
                ('commande_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livraison.commande')),
                ('prestataire_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livraison.prestatairedelivraison')),
            ],
        ),
    ]
