# Generated by Django 5.0.6 on 2024-09-19 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0002_alter_commande_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='client_id',
            new_name='utilisateur_id',
        ),
    ]
