# Generated by Django 5.0.6 on 2024-09-19 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0003_rename_client_id_commande_utilisateur_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='commande_id',
            new_name='id',
        ),
    ]
