# Generated by Django 5.0.6 on 2024-09-19 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0004_rename_commande_id_commande_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('adresse', models.TextField()),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('livreur', 'Livreur'), ('client', 'Client')], default='client', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='commande',
            name='utilisateur_id',
        ),
        migrations.AddField(
            model_name='commande',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
