# Generated by Django 5.0.6 on 2024-09-19 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0005_client_remove_commande_utilisateur_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='livraison.client'),
        ),
    ]
