name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker images
        run: |
          docker build -t node-app:latest ./frontend/node-app
          docker build -t django-app:latest ./backend/django-app

      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v1
        with:
          version: '1.21.0'

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f kubernetes/node-deployment.yaml
          kubectl apply -f kubernetes/django-deployment.yaml
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}

      - name: Notify
        run: echo 'Build and deployment completed!'
