# Generated by Django 5.1.1 on 2024-09-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyonmall', '0002_alter_commandes_total_panier_articlepanier'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandes',
            name='charge_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='commandes',
            name='statut',
            field=models.CharField(max_length=20),
        ),
    ]
