# Generated by Django 5.1.1 on 2024-09-25 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyonmall', '0003_commandes_charge_id_alter_commandes_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandes',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
