# Generated by Django 5.1.1 on 2024-09-25 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lyonmall', '0004_commandes_stripe_payment_intent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commandes',
            old_name='stripe_payment_intent_id',
            new_name='payment_intent_id',
        ),
    ]
