global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['node-app:9100', 'django-app:9100']
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
