apiVersion: v1
kind: Service
metadata:
  name: django-service
  labels:
    app: django-app
spec:
  type: LoadBalancer  # Expose le service sur un LoadBalancer
  selector:
    app: django-app    # Correspond aux pods avec ce label
  ports:
    - protocol: TCP
      port: 80         # Port exposé au niveau du service
      targetPort: 8000 # Port sur lequel l'application Django écoute dans le pod

---
apiVersion: v1
kind: Service
metadata:
  name: node-service
  labels:
    app: node-app
spec:
  type: LoadBalancer  # Expose le service sur un LoadBalancer
  selector:
    app: node-app     # Correspond aux pods avec ce label
  ports:
    - protocol: TCP
      port: 80        # Port exposé au niveau du service
      targetPort: 3000 # Port sur lequel l'application Node.js écoute dans le pod
