# .github/workflows/deploy.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # ou "master", selon ta configuration

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd backend/node  # Va dans le répertoire backend/node
          npm install

      - name: Run tests
        run: |
          cd backend/node  # Assure-toi d'être dans backend/node
          npm test

      - name: Build Docker image
        run: |
          docker build -t backend:latest ./backend/node  # Assure-toi de pointer vers backend/node

      - name: Push Docker image to registry
        run: |
          docker tag backend:latest your_dockerhub_account/backend:latest
          docker push your_dockerhub_account/backend:latest
