# .github/workflows/deploy.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Mise à jour de l'action checkout à la version v3

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Mise à jour de l'action setup-node à la version v3
        with:
          node-version: '16'  # Utilise Node.js 16, ou tu peux aussi utiliser Node.js 18 ou 20 si nécessaire

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Run tests
        run: npm test

      - name: Build Docker image
        run: |
          docker build -t backend:latest ./backend

      - name: Push Docker image to registry
        run: |
          docker tag backend:latest your_dockerhub_account/backend:latest
          docker push your_dockerhub_account/backend:latest
