name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # ou "master", selon ta configuration

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Mettre à jour la version de Node.js si nécessaire

      - name: Install dependencies
        run: |
          cd backend/node
          npm install

      - name: Install kubectl manually
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl


      - name: Build Docker images for backend and frontend
        run: |
          docker build -t backend-node:latest ./backend/node
          docker build -t backend-django:latest ./backend/django_project
          docker build -t frontend-angular:latest ./frontend/lyonmall-frontend
          
      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        
      - name: Push Docker images to Docker Hub
        run: |
          docker tag backend-node:latest ${{ secrets.DOCKER_USERNAME }}/backend-node:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/backend-node:latest
          docker tag backend-django:latest ${{ secrets.DOCKER_USERNAME }}/backend-django:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/backend-django:latest
          docker tag frontend-angular:latest ${{ secrets.DOCKER_USERNAME }}/frontend-angular:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend-angular:latest

      - name: Check Kubernetes cluster status
        run: kubectl get nodes --kubeconfig=kubeconfig.yaml

      - name: Deploy to Kubernetes
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
          kubectl --kubeconfig=kubeconfig.yaml apply -f kubernetes/node-deployment.yaml
          kubectl --kubeconfig=kubeconfig.yaml apply -f kubernetes/django-deployment.yaml

      - name: Notify
        run: echo 'Build and deployment completed!'
